variable "region" {
  type        = string
  description = "Artifact Registry Region"
}

variable "repository_id" {
  type        = string
  description = "ID / Name of repository Artifact Registry"
}

variable "format" {
  type    = string
  default = "DOCKER"
}

variable "description" {
  type    = string
  default = "Docker repository generated by Terraform"
}